# Generated by Django 2.1.7 on 2019-04-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='textpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('html', models.TextField(default='', max_length=30000)),
            ],
        ),
    ]
