# Generated by Django 2.1.7 on 2019-04-08 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textpage', '0004_auto_20190407_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='textpage.textpage'),
        ),
    ]
