# Generated by Django 2.1.7 on 2019-04-08 00:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('textpage', '0005_menu_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='menuitem',
        ),
    ]
